# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: measurement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11measurement.proto\x12\x0bmeasurement\"M\n\x0eRequestMessage\x12;\n\x13measurement_records\x18\x01 \x03(\x0b\x32\x1e.measurement.MeasurementRecord\"\x91\x01\n\x11MeasurementRecord\x12\n\n\x02id\x18\x01 \x01(\x03\x12-\n\x0cmeasurerName\x18\x02 \x01(\x0e\x32\x17.measurement.PersonName\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x10\n\x08\x64ownload\x18\x04 \x03(\x01\x12\x0e\n\x06upload\x18\x05 \x03(\x01\x12\x0c\n\x04ping\x18\x06 \x03(\x01\"P\n\x0fResponseMessage\x12=\n\x14measurement_averages\x18\x01 \x03(\x0b\x32\x1f.measurement.MeasurementAverage\"\x92\x01\n\x12MeasurementAverage\x12\n\n\x02id\x18\x01 \x01(\x03\x12-\n\x0cmeasurerName\x18\x02 \x01(\x0e\x32\x17.measurement.PersonName\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x10\n\x08\x64ownload\x18\x04 \x01(\x01\x12\x0e\n\x06upload\x18\x05 \x01(\x01\x12\x0c\n\x04ping\x18\x06 \x01(\x01*9\n\nPersonName\x12\x0c\n\x08kristyna\x10\x00\x12\t\n\x05jirka\x10\x01\x12\x08\n\x04petr\x10\x02\x12\x08\n\x04jana\x10\x03\x62\x06proto3')

_PERSONNAME = DESCRIPTOR.enum_types_by_name['PersonName']
PersonName = enum_type_wrapper.EnumTypeWrapper(_PERSONNAME)
kristyna = 0
jirka = 1
petr = 2
jana = 3


_REQUESTMESSAGE = DESCRIPTOR.message_types_by_name['RequestMessage']
_MEASUREMENTRECORD = DESCRIPTOR.message_types_by_name['MeasurementRecord']
_RESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['ResponseMessage']
_MEASUREMENTAVERAGE = DESCRIPTOR.message_types_by_name['MeasurementAverage']
RequestMessage = _reflection.GeneratedProtocolMessageType('RequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTMESSAGE,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:measurement.RequestMessage)
  })
_sym_db.RegisterMessage(RequestMessage)

MeasurementRecord = _reflection.GeneratedProtocolMessageType('MeasurementRecord', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENTRECORD,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:measurement.MeasurementRecord)
  })
_sym_db.RegisterMessage(MeasurementRecord)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEMESSAGE,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:measurement.ResponseMessage)
  })
_sym_db.RegisterMessage(ResponseMessage)

MeasurementAverage = _reflection.GeneratedProtocolMessageType('MeasurementAverage', (_message.Message,), {
  'DESCRIPTOR' : _MEASUREMENTAVERAGE,
  '__module__' : 'measurement_pb2'
  # @@protoc_insertion_point(class_scope:measurement.MeasurementAverage)
  })
_sym_db.RegisterMessage(MeasurementAverage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSONNAME._serialized_start=492
  _PERSONNAME._serialized_end=549
  _REQUESTMESSAGE._serialized_start=34
  _REQUESTMESSAGE._serialized_end=111
  _MEASUREMENTRECORD._serialized_start=114
  _MEASUREMENTRECORD._serialized_end=259
  _RESPONSEMESSAGE._serialized_start=261
  _RESPONSEMESSAGE._serialized_end=341
  _MEASUREMENTAVERAGE._serialized_start=344
  _MEASUREMENTAVERAGE._serialized_end=490
# @@protoc_insertion_point(module_scope)
